### ISSUE TITLE
Installing Scorpio

### ISSUE THREAD

**Issue by VezirChess** [dshawul/Scorpio#10]
I am a new user for scorpio.But I don't know that how can I open it in windows.The GUI's gives error when ı try to open it in GUI.Can you tell me how can I install it on Windows? ( step by step )

**Comment by dshawul** [comment]
Use the following install script https://github.com/dshawul/Scorpio/releases/download/2.9.0/install.sh

On windows you need something to run shell scripts cygwin, mysys ..
Edit the 2 lines in install.sh to:
```
  6 OS=windows          # OS is either ubuntu/centos/windows
  8 DEV=cpu            # Device is either gpu/cpu
```
to install cpu version. If you have GPUs change device to gpu.

Then run install.sh and it should successfully install everything for you.

**Comment by VezirChess** [comment]
No, install.sh doesn't install with msys.( I can't run it with cygwin. ) It only downloads nets-ccrl-cegt and egbbdll64-nn-windows-cpu and that is all.
After downloading it exits and creates wget.exe.stackdump

**Comment by dshawul** [comment]
Just tried it with mysys and it works. The only issue i had was mysys produces paths like /c/Users which i had to replace with c:/Users in scorpio.ini.  Also testest with cygwin with no problem so i am not sure what issues you have but it is not with the script.
