### ISSUE TITLE
Invalid UCI move (f2f1Q) triggers an exception in python-chess and breaks HIARCS GUI

### ISSUE THREAD

**Issue by kennyfrc** [dshawul/Scorpio#17]
Hi there, I chanced upon a uci typo error when trying to set up scorpio as a lichess bot. This breaks `python-chess` and HIARCS analysis. 

To replicate the issue:

```
./scorpio
uci
position fen 1B6/p5p1/N4p2/1P6/2p1k3/8/P2R1p2/7K b - - 1 40
go nodes 1
bestmove f2f1Q
```

I used MCTS+NNUE with this [net](https://github.com/kennyfrc/nnue-networks/releases/tag/first-run).

The capital "Q" breaks python-chess and breaks the analysis feature of HIARCS. The correct uci move for promotions is lowercase (f2f1q).

I suspect this creates crashes as well when setting up scorpio as a UCI engine in other guis.

**Comment by kennyfrc** [comment]
Note that this is also true for other promotions "R", "N", etc

**Comment by dshawul** [comment]
Thanks! bb4cbe2715578492d4f7565894afe2aa should fix this bug.
