### ISSUE TITLE
Scorpio 2.9.0 Resigns Bug

### ISSUE THREAD

**Issue by B-Sing** [dshawul/Scorpio#9]
setup:
 
Scorpio 2.9.0 MCTS + NN, Windows 10, Arena 3.5.1 GUI engine tournament. Scorpio running on CPU only, neural networking disabled.

Scorpio resigns bug:

Bug only occurs after Scorpio resigns a game. Bug does not occur after Scorpio wins a game, draws a game or after Scorpio loses a game to mate. Until the time that Scorpio resigns a game the tournament will proceed as expected without error.

Scorpio observed behaviour after the engine resigns a game as white:

The next game will commence.
The opposition engine will announce the move count as zero and make the first move as white in accordance with the opening book.
Scorpio will not announce the move count neither will it announce the move in accordance with the book.
Scorpio will announce "Engine already calculating".
Scorpio will then remain idle until the engine, black in this case, forfeits on time.
At the start of all subsequent games in the tournament Scorpio will announce "Engine already calculating" and will then forfeit on time.

**Comment by dshawul** [comment]
Scorpio is an xboard engine, which can resign, unlike other UCI engines who don't. Some GUIs may have a problem with that. A solution could be to turn of resign in scorpio.ini by increasing resign value to something like 1000000

**Comment by B-Sing** [comment]
Thank you for your helpful comments. I see now that this particular GUI 
(Arena) can also have trouble with other xboard engines that resign. 
Your workaround of adjusting the resign number upwards for Scorpio not 
only prevents the resign but also allows the GUI to adjudicate the loss, 
before mate occurs. A good solution.
